class DryService

  def call
    puts obiwan
    "Hello there."
  end

protected

  def obiwan
    <<~STR
      oxxxxxxxxxxxxxxxxxxxl,',,;:...  .... ..,:lxxlc,''''.';loxkkkxkkkkxxxkkkkkxxxkkkx
      XMMMMMMMMMMMMMMMMXx;'.:dl:,'.   .......;lldO0X0k0NNXNWNWMMMMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMMMMMMKo'.'''.'.. .  ...  ..,:looxxddkO00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMMMMNx'..'......   .....,lkKWNOxO0XKkdc;,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMMMNo. ..  .'..... .;c:lKMMMMXxooooddxc',,,lkXNWMMMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMMNo.    ':'.',..;ooONNNMMMMW0kOOO0KXXO::OKkc:ckWMMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMWd.  ..;:l;..,lk0ddXMMMMMMMMMMMMMMMMMWK:,kWN:.;xNMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMMk.  .;d:.,'.;lolckNMMMMMMMMMMMMMMXXMWWWXc,OMd.coOMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMN:   .c;..;:..';,xWMMMMMMMMMMMMMMMNNWKKWMK;:XO,;cxWMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMMk.    ...:o. :c:dXMMMMMMMMMMMMMMMMMMKcdMMO,.xWx'.dWMMMMMMMMMMMMMMMMMMMN
      XMMMMMMMN:     ..;;..cdoOWMMMMMMMMMMMMNNWMMMNo,kMMkc,,OXc.xMMMMMMMMMMMMMMMMMMMMN
      NMMMMMMWx.     .l, .lNWWMMMMMMMMMMMMMMWNWMMMK,'llolxo.,kl'OMMMMMMMMMMMMMMMMMMMMN
      NMMMMMMWl      ,;  ,xdkNMMWNNWMMMMMMMMMMMMMMKl,;cl:dl..lc,kNWMMMMMMMMMMMMMMMMMMN
      XMMMMMMM0'     ..  .. .kMMWK0KXNMMMMMMWWWMMNXK0OO0Kkc..;::ooldxOKXXWMMMMMMMMMMMN
      XMMMMMMMk. .    .'   .lKWWKddxdONWWMMKl:doldocc,.':OKoc:l0XKKKKKNNNWMMMMMMMMMMMN
      XMMMMMMWl cx' ..'.  .kMWWNOcckKNMWWMMK;.:..lo:'..,cOW0odKWWMMMMMMMMMMMMMMMMMMMMN
      XMMMMMMWk';l. ...   .OMMMMWXKWMMMMMMMMd.,:''kX0olxXWWxloodkKKOkOXWMMMMMMMMMMMMMN
      NMMMMMMMWx..:;.:'    cXMMMMMMMMMMMMMMMx..lO;'OWKKkoOWO,.',;;,,:d0XNWMMMMMMMMMMMN
      WMMMMMMMMX; ;;.....  '0MMMMMMMMMMMMMMM0,.:Xk:OMMNocKMk;xKKK0OOKNNWWMMMMMMMMMMMMN
      KXNMMMMMMWo  .....,. :OWMMMMMMMMMWX0XNx,.,xdc0MMN0XMMx:0MMMMMMMMMMMMMMMMMMMMMMMN
      0Kkx0WMMMM0' .lc.,:' ;xXMMMMMMMWWKxdkkdl;::,cO0KMMMMMO;oKXWMMMMMMMMMMMMMMMMMMMMN
      KMWXOkKWMMWl.,dc..,. ;0WMMMMMWWWWWWWMNOO0KKd:ooxNMMMWkckNWMMMMMMMMMMMMMMMMMMMMMX
      0WMMWXOoxXWx......,,..oWMMMMWXXWWMMMMMMMMMXOdodxKMMMk;dWMWWMMMMMMMMMMMMMMMMMMMMX
      ONXWMMW0c'cOd,. ..,,'.;KNXNWX0XXXX0OxocloxoodoOxOMMX:;OO0XNNNWNWMMMMMMMMMMMMMMMX
      KWN0x0XXXk:,cc. . ';,:cdx;'oXXNOcokkkxddoc'..,cokKXd,kWNNMWXXWWWWMMMWWMMMMMMMMMX
      XMMNx:',OMW0xkd;. .;:::;;. 'd0WKxxO0NNk:;:;'oKOclodOKWWOdxkKWNX0okWMMMMMMMMMMMMX
      XMMMMXl.'OWMMMWXO; .'oo.   ;ONMMMMNXNWKO0XWxdWWx::coOWMXkl;:dk0d.,KWXNMMMMMMMMMX
      XMMMMWWO::OXXK00x'  .:lc,.,OMMMMMMMX0XNKk0WX0K0K0:. .dNMMWKkolOk:oXWXNMMMMMMMMMK
      XMMNXX0xoc:,.....    '';;'cxkXMMMMMNXNWWNNWWWNkOXc  ;ccOXWMWNKXXXWMMMMMMMMMMMMMX
      xxo:,'..   . ..      .'.''...oWMMMMMMMMMMW0OKKO0O:.'0Kc,;:cd0XNNWMMMMMMMMMMMMMMX
      ..........';;,.    ..';;';;:'cNMMMMMMMMMMXdlxOK0l''dWW0o'   .,;;:lkKNWMMMMWNNWMK
      ;o:cOK00kxk00c.   .cKKxo' .l;'kMWWMWWWKOOOk0XN0l'.:xN0ol;...':'.. ..,:lodkKNXXWK
      0Kk0NWMMWWMMO';l..'cKMWKl. ':;;ddo0XNWXkxKN0xl,.,ddk0:,d0d.;xx,,l;..'.....';col;
      KWWMWMMMMMMWd.cKOOXooNMMW0l,.,'..:d0WMW0dxdoo,'l0KK0:,kN0cdXNXx0Kl;;::;;'.......
      XMMMMMMMMMMXo'oWMWM0lOMMMMMXxc;'':oooxxold00lckKXWK:;OMXk0WMMWXNWNXXXKxoodddxdc.
      OXKXXXKXXKXxc,cKXKX0clXXNNNNNKd:cxKKO0XNNNKc;xdlOK:.dX0dxXKXXXKXXXXKXKKKkxkkxxd;

    STR
  end
end
